"""
Trains a 3-input → 6-hidden → 3-output LIF spiking neural network
using snnTorch surrogate gradient descent.

Inputs:  F1 (spike width), F2 (peak timing), F3 (rise ratio)
Outputs: Neuron A (interneuron), Neuron B (pyramidal), Noise

"""

import numpy as np
import torch
import torch.nn as nn
import snntorch as snn
from snntorch import surrogate
from torch.utils.data import DataLoader, TensorDataset

# Hyperparameters
NUM_STEPS  = 256     # integration window length (timesteps per sample)
BETA       = 0.95    # LIF membrane decay factor (τ approximation)
BATCH_SIZE = 64
EPOCHS     = 50
LR         = 1e-3
N_INPUTS   = 3       # F1, F2, F3
N_HIDDEN   = 6
N_OUTPUTS  = 3       # Neuron A, Neuron B, Noise


# Rate encoder
def features_to_spikes(features, num_steps=NUM_STEPS):
    """
    Convert scalar feature values to Poisson spike trains.
    Each feature value f is the probability of firing at each timestep.
    Higher f → more spikes → more LIF membrane charge → more output spikes.

    Input shape:  (batch, 3)
    Output shape: (num_steps, batch, 3)
    """
    spikes = torch.zeros(num_steps, features.shape[0], features.shape[1])
    for t in range(num_steps):
        spikes[t] = torch.bernoulli(torch.clamp(features, 0.0, 1.0))
    return spikes


# SNN architecture
class SpikeSorter(nn.Module):
    
    def __init__(self):
        super().__init__()
        spike_grad = surrogate.fast_sigmoid(slope=25)

        self.fc1  = nn.Linear(N_INPUTS,  N_HIDDEN,  bias=False)
        self.lif1 = snn.Leaky(beta=BETA, spike_grad=spike_grad)

        self.fc2  = nn.Linear(N_HIDDEN,  N_OUTPUTS, bias=False)
        self.lif2 = snn.Leaky(beta=BETA, spike_grad=spike_grad)

    def forward(self, x_spikes):
        """
        x_spikes: (num_steps, batch, 3)
        Returns:  (num_steps, batch, 3) — output spike tensor
        """
        mem1     = self.lif1.init_leaky()
        mem2     = self.lif2.init_leaky()
        spk2_rec = []

        for t in range(x_spikes.shape[0]):
            cur1       = self.fc1(x_spikes[t])
            spk1, mem1 = self.lif1(cur1, mem1)
            cur2       = self.fc2(spk1)
            spk2, mem2 = self.lif2(cur2, mem2)
            spk2_rec.append(spk2)

        return torch.stack(spk2_rec, dim=0)


# Training loop
def train():
    # Load features generated by data/simulate_waveforms.py
    X_feat = np.load("data/X_features.npy")   # shape (3000, 3)
    y      = np.load("data/y_labels.npy")      # shape (3000,)

    X_tensor = torch.FloatTensor(X_feat)
    y_tensor = torch.LongTensor(y)
    dataset  = TensorDataset(X_tensor, y_tensor)
    loader   = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    model     = SpikeSorter()
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    loss_fn   = nn.CrossEntropyLoss()

    print(f"Training 3→6→3 LIF SNN for {EPOCHS} epochs...\n")
    best_acc = 0.0

    for epoch in range(EPOCHS):
        model.train()
        total_loss, correct, total = 0.0, 0, 0

        for X_batch, y_batch in loader:
            optimizer.zero_grad()

            # Convert features to Poisson spike trains
            x_spikes = features_to_spikes(X_batch)

            # Forward pass — sum output spikes for population vote
            spk_out      = model(x_spikes)           # (T, batch, 3)
            spike_counts = spk_out.sum(dim=0)        # (batch, 3)
            loss         = loss_fn(spike_counts, y_batch)

            loss.backward()
            optimizer.step()

            preds      = spike_counts.argmax(dim=1)
            correct   += (preds == y_batch).sum().item()
            total     += y_batch.size(0)
            total_loss += loss.item()

        acc = 100.0 * correct / total
        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), "model/spikesort_weights.pt")

        if (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch+1:>3}/{EPOCHS}  "
                  f"Loss: {total_loss/len(loader):.4f}  "
                  f"Acc: {acc:.1f}%  "
                  f"{'← best' if acc == best_acc else ''}")

    print(f"\nBest accuracy: {best_acc:.1f}%")
    print("Saved: model/spikesort_weights.pt")
    return model


if __name__ == "__main__":
    train()
