"""
export_weights.py
─────────────────
Loads trained PyTorch weights, converts to Q8 signed 8-bit fixed-point,
and writes a Verilog localparam block ready to paste into snn_core.v.

Q8 format: integer = round(float × 128), clipped to [-128, 127]
Scale factor 128 means 1.0 float → 128 integer, 0.5 float → 64 integer.

Run from project root AFTER model/train_snn.py:
  python export/export_weights.py
"""

import numpy as np
import torch
import json
import sys
import os

# Import SpikeSorter from model folder
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'model'))
from train_snn import SpikeSorter


# ── Q8 conversion ──────────────────────────────────────────────────────────────
def to_q8(tensor):
    """
    Convert float32 weight tensor to signed 8-bit Q8 fixed-point.
    Scale factor: 128  (i.e. 1.0 float → 128 integer)
    Clipped to [-128, 127] to fit int8 range.
    """
    scaled  = tensor.detach().numpy() * 128.0
    clipped = np.clip(np.round(scaled), -128, 127).astype(np.int8)
    return clipped


# ── Verilog localparam formatter ───────────────────────────────────────────────
def format_verilog(W_ih, W_ho):
    """
    Generate Verilog SystemVerilog localparam array declarations.
    W_ih shape: (6, 3)  — hidden layer weights  [6 neurons × 3 inputs]
    W_ho shape: (3, 6)  — output layer weights  [3 neurons × 6 hidden]
    """
    rows_ih, cols_ih = W_ih.shape
    rows_ho, cols_ho = W_ho.shape

    lines = []
    lines.append("    // ── Q8 weights: paste between the markers in snn_core.v ──────────")
    lines.append(f"    // W_IH [{rows_ih} hidden × {cols_ih} inputs]  — generated by export/export_weights.py")
    lines.append(f"    localparam signed [7:0] W_IH [0:{rows_ih-1}][0:{cols_ih-1}] = '{{")
    for h in range(rows_ih):
        vals  = ", ".join(f"{int(W_ih[h, c]):4d}" for c in range(cols_ih))
        comma = "," if h < rows_ih - 1 else ""
        lines.append(f"        '{{ {vals} }}{comma}   // H{h}")
    lines.append("    };")
    lines.append("")
    lines.append(f"    // W_HO [{rows_ho} outputs × {cols_ho} hidden]")
    lines.append(f"    localparam signed [7:0] W_HO [0:{rows_ho-1}][0:{cols_ho-1}] = '{{")
    for o in range(rows_ho):
        vals  = ", ".join(f"{int(W_ho[o, h]):4d}" for h in range(cols_ho))
        comma = "," if o < rows_ho - 1 else ""
        lines.append(f"        '{{ {vals} }}{comma}   // O{o}")
    lines.append("    };")
    lines.append("    // ── end weights ───────────────────────────────────────────────────")

    return "\n".join(lines)


# ── Main ───────────────────────────────────────────────────────────────────────
def export():
    print("Loading trained model from model/spikesort_weights.pt ...")
    model = SpikeSorter()
    model.load_state_dict(torch.load("model/spikesort_weights.pt",
                                     map_location="cpu"))
    model.eval()

    W_ih = to_q8(model.fc1.weight)   # shape (6, 3)
    W_ho = to_q8(model.fc2.weight)   # shape (3, 6)

    print(f"\nW_IH (6×3) — hidden layer weights:")
    print(W_ih)
    print(f"\nW_HO (3×6) — output layer weights:")
    print(W_ho)

    # Save JSON reference
    weights_dict = {
        "W_ih": W_ih.tolist(),
        "W_ho": W_ho.tolist(),
        "note": "Q8 format: integer = round(float * 128), scale factor 128"
    }
    with open("export/weights_q8.json", "w") as f:
        json.dump(weights_dict, f, indent=2)
    print("\nSaved: export/weights_q8.json")

    # Save Verilog block
    verilog_str = format_verilog(W_ih, W_ho)
    with open("export/weights_q8.vh", "w") as f:
        f.write(verilog_str + "\n")
    print("Saved: export/weights_q8.vh")

    # Print copy-paste block
    print("\n" + "=" * 66)
    print("COPY THE BLOCK BELOW AND PASTE INTO rtl/snn_core.v")
    print("=" * 66)
    print(verilog_str)
    print("=" * 66)


if __name__ == "__main__":
    export()
